### ISSUE TITLE
Unable to compile bmc on Linux Mint 18.3 (with Ubuntu 16.04 as a base)

### ISSUE THREAD

**Issue by captainkats** [mlang/bmc#9]
captaink@KingdomOfGod ~/bin/bmc $ git clone --quiet https://github.com/mlang/bmc.git
captaink@KingdomOfGod ~/bin/bmc $ git submodule --quiet update --init --recursive
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
captaink@KingdomOfGod ~/bin/bmc $ cd bmc
captaink@KingdomOfGod ~/bin/bmc/bmc $ git submodule --quiet update --init --recursive
captaink@KingdomOfGod ~/bin/bmc/bmc $ cmake .
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/captaink/bin/bmc/bmc/CMakeFiles/CMakeOutput.log".
See also "/home/captaink/bin/bmc/bmc/CMakeFiles/CMakeError.log".

Dependencies installed ok:
doxygen is already the newest version (1.8.11-1).
libboost-program-options-dev is already the newest version (1.58.0.1ubuntu1).
libboost-test-dev is already the newest version (1.58.0.1ubuntu1).
libfluidsynth-dev is already the newest version (1.1.6-3).
cmake is already the newest version (3.5.1-1ubuntu3).
libicu-dev is already the newest version (55.1-7ubuntu0.3).

Any advice?
Thanks.

**Comment by mlang** [comment]
The error seems to indicate you have no C++ compiler installed.
Try installing "build-essential" or "g++".

-- 
CYa,
  ⡍⠁⠗⠊⠕

**Comment by captainkats** [comment]
Thank you! It was one of the missing dependencies. 
However cmake continued to complain for other missing development files, like Python, xerces, xsdcxx, sphinx & lilypond. With these the compiling was successful.
Tried also to install qt5-dev libs & warned about needing some more multimedia & svg libs but were not required for compiling the base cmd program.

Probably the readme file needs to be updated with all the dependencies needed. Thanks.
